---
username: netops
password: CHANGE_ME
connection_options:
  netmiko:
    extras:
      conn_timeout: 20
      banner_timeout: 30
      auth_timeout: 20
      fast_cli: false
data:
  domain_name: example.local
  ntp_servers:
    - 10.10.10.10
    - 10.10.10.11
  syslog_servers:
    - 10.10.20.10
  snmp_location: TEMPLATE
